tab_spaces = 4
hard_tabs = false
edition = "2021"
imports_granularity = "crate"
newline_style = "unix"
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true
match_block_trailing_comma = true
comment_width = 119
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
wrap_comments = true
